# Generated by Django 4.2.1 on 2023-05-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('logo', models.ImageField(upload_to='logo', verbose_name='лаготип курса')),
                ('phone', models.CharField(max_length=255, verbose_name='телеыонный номер')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('locate', models.CharField(max_length=255, verbose_name='адрес')),
                ('facebook', models.URLField(verbose_name='сслылка на facebook')),
                ('instagram', models.URLField(verbose_name='сслыка на instagram')),
                ('youtube', models.URLField(verbose_name='ссылка на youtube')),
            ],
            options={
                'verbose_name': 'настройка',
                'verbose_name_plural': 'настройки',
            },
        ),
    ]
